# Generated by Django 3.1.7 on 2021-05-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_question_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='upvotes',
        ),
    ]
