# Generated by Django 3.1.7 on 2021-06-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='donw_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
