# Generated by Django 3.1.7 on 2021-06-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210624_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='donw_votes',
            new_name='down_votes',
        ),
    ]
