# Generated by Django 3.1.7 on 2021-06-24 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_auto_20210624_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='answer',
            name='up_votes',
            field=models.ManyToManyField(related_name='ans_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
