# Generated by Django 3.1.7 on 2021-06-24 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20210624_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='down_votes',
            field=models.ManyToManyField(related_name='down_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='up_votes',
            field=models.ManyToManyField(related_name='up_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
