# Generated by Django 3.1.7 on 2021-07-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210624_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
