# Generated by Django 3.1.7 on 2021-05-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='/img/default_profile_img.png', null=True, upload_to='profile-img/'),
        ),
    ]
