# Generated by Django 3.1.7 on 2021-05-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210504_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='assets/default-profile.png', null=True, upload_to='profile-img/'),
        ),
    ]
