# Generated by Django 3.1.7 on 2021-04-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210413_2114'),
        ('accounts', '0004_auto_20210418_0947'),
    ]

    operations = [
    ]
